#!/usr/bin/expect -f
#
set force_conservative 0  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}
#
set timeout -1
spawn bash Anaconda3-2023.09-0-Linux-x86_64.sh
match_max 100000
expect -exact "\r
Welcome to Anaconda3 2023.09-0\r
\r
In order to continue the installation process, please review the license\r
agreement.\r
Please, press ENTER to continue\r
>>> "
send -- "\r"
expect -exact "\r
HE POSSIBILITY OF SUCH DAMAGE.\r
\r
\[7m--More--\[27m"
send -- "q"
expect -exact "\r\[K\r
Do you accept the license terms? \[yes|no\]\r
\[no\] >>> "
send -- "yes\r"
expect -exact "yes\r
\r
Anaconda3 will now be installed into this location:\r
/home/ubuntu/anaconda3\r
\r
  - Press ENTER to confirm the location\r
  - Press CTRL-C to abort the installation\r
  - Or specify a different location below\r
\r
\[/home/ubuntu/anaconda3\] >>> "
send -- "\r"
expect -exact "\r
PREFIX=/home/ubuntu/anaconda3\r
You can undo this by running `conda init --reverse \$SHELL`? \[yes|no\]\r
\[no\] >>> "
send -- "yes\r"
expect eof
